### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by sinework**
### In this milestone:
friendships are implemented with 2 rows for mutual friendship

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @sinework  ! 👋 👋 

### You have done well so far :clap: However, there are changes required for you to make for this milestone to be approved. Kindly work on them and submit them for another code review.

**Recommended**

- [x] Fix the errors in your tests.
- [x] Add negative case scenarios to the tests.
- [x] User has to accept friendship request to start a friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). 
- When a logged-in user views the profile of another user who is not yet a friend, he should not be able to see the posts of that person.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:

__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by sinework** [comment]
Can you send me a screenshot of the failing tests? 
as you can see below, all the test cases are passing on my side.
NoTestFailing

**Comment by Temmarie** [comment]
Hi there, if it's not failing on your side, then you can skip that comment. Just be sure to address it in your next submission that the tests are all passing on your side.

Screenshot (157)

**Comment by sinework** [comment]
Thank you! I rerun the test and it is still passing. I'll run more tests after I add more test cases.

**Comment by sinework** [comment]
### Thank you for the comments 

**

**- I have restricted access to the user's post unless the friendship is confirmed. 
- Negative test cases are in the user-spec as you can see below**

**

negative test cases

**

- 

- **> No test case is failing on my end**

**

**Review by teekaytech — APPROVED** [review]
# Status: Approved :green_circle: 

### Congratulations team, this milestone has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

You can now merge to development. :+1: 
Good luck with your next tasks.

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
